# Use postgres/example user/password credentials
version: '3.3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: suade
    volumes:
      - type: bind
        source: ./docker-db
        target: /docker-entrypoint-initdb.d
    ports:
      - 5432:5432
